### PR TITLE
event_date_id param and scope

### PR DESCRIPTION
**Pull request by PhilNorman2**
Added an event_date_id parameter on the events endpoint.  The response returns the event containing the event_date represented by the event_date_id.

Example request:

http://localhost:8888/api/events?event_date_id=16195 

Example response:

<pre>
{
    "events": [
        {
            "id": 5596,
            "address": "3960 BROOKHAM DR  ",
            "city": "GROVE CITY",
            "state": "OH",
            "zip": "43123",
            "agency_id": 6,
            "latitude": "39.8862352",
            "longitude": "-83.05538713",
            "name": "Drive Thru Wednesday Evening",
            "estimated_distance": "",
            "exception_note": "",
            "event_details": "This is a drive thru distribution. Wear a mask and make sure your trunk is cleaned out. Please, no more than 5 families being served per vehicle. Please pre-register on FreshTrak.com.",
            "agency_name": "Mid-Ohio Foodbank - Kroger Community Pantry",
            "agency_phone": "614-317-9487",
            "event_dates": [
                {
                    "id": 16194,
                    "event_id": 5596,
                    "capacity": 300,
                    "accept_walkin": 1,
                    "accept_reservations": 0,
                    "accept_interest": 1,
                    "start_time": "5 PM",
                    "end_time": "7 PM",
                    "date": "2020-11-04"
                },
                {
                    "id": 16195,
                    "event_id": 5596,
                    "capacity": 300,
                    "accept_walkin": 1,
                    "accept_reservations": 0,
                    "accept_interest": 1,
                    "start_time": "5 PM",
                    "end_time": "7 PM",
                    "date": "2020-11-11"
                },
                {
                    "id": 16196,
                    "event_id": 5596,
                    "capacity": 300,
                    "accept_walkin": 1,
                    "accept_reservations": 0,
                    "accept_interest": 1,
                    "start_time": "5 PM",
                    "end_time": "7 PM",
                    "date": "2020-11-18"
                },
                {
                    "id": 16197,
                    "event_id": 5596,
                    "capacity": 300,
                    "accept_walkin": 1,
                    "accept_reservations": 0,
                    "accept_interest": 1,
                    "start_time": "5 PM",
                    "end_time": "7 PM",
                    "date": "2020-11-25"
                }
            ],
            "forms": [
                {
                    "id": 91,
                    "display_age_adult": 18,
                    "display_age_senior": 60
                }
            ],
            "service_category": {
                "id": 15,
                "service_category_name": "Prepack Pantry"
            }
        }
    ]
}
</pre>

### CODE REVIEW

**Comment by PhilNorman2** [comment]
ToDo: Write tests

**Comment by sarath-yerra** [comment]
Thanks Phill

**Comment by sarath-yerra** [comment]
Changes Looks Good. 
To show the reservations on the logged home page this api helps in not making multiple api calls to event_dates and event.
Right now we have EventDate_id on the User(Registration API).Using this eventdate_id we will make direct calls to event using  {root}/api/events?event_date_id=event_date_id from here we have agency_name, phone,address etc adn event and event_dates details .

**Comment by sarath-yerra** [comment]
Sample User Response:

    {
        "id": 101,
        "user_id": 1,
        "event_date_id":event_id,
        "created_at": "2020-11-02T19:39:39.322Z",
        "updated_at": "2020-11-02T19:39:39.322Z",
        "event_slot_id": null
    }
]

**Review by sarathyerra14 — APPROVED** [review]

**Pull request merged**
