### PR TITLE
Db refresh

### PR DESCRIPTION
**Pull request by PhilNorman2**

### CODE REVIEW

**Comment by PhilNorman2** [comment]
Shouldn't have merge issue, will try with a new branch name.

**Review by davidpickering — APPROVED** [review]
Thanks for updating the seed file Phil!

**Comment by PhilNorman2** [comment]
> Thanks for updating the seed file Phil!

Hi David.  Glad to help out.  There is a merge issue with the seed.sql.zip file.  I have never seen that before.  This is a binary file so not exactly sure how to deal with it.  Looking at some options.

**Comment by PhilNorman2** [comment]
Had problems with binary merge.   This is replaced with PR #72

**Pull request closed without merging**
